In [6]:
import pandas as pd

In [10]:
folder = Path(r'X:\00_ЛабГрад_ПО\09_Сотрудники\Глазов Ю.А\izhevsk\weights')
files = [f.name for f in folder.iterdir() if f.is_file()]
files

['weights_20260212.csv']

In [11]:
file_path = folder / 'weights_20260212.csv'

In [13]:
weigths = pd.read_csv(file_path).iloc[:-1]

In [14]:
weigths

,Unnamed: 0,ЛЛМ,ЕП,УС,МЖ,ИР,ЛИ,АТ,АД,РХ,Unnamed: 10,Unnamed: 11
0,Критерий интервала маршрута НГПТ (Н1),20,5,8,NaN,14,10,NaN,NaN,NaN,9.0,"12,5"
1,Критерий времени работы маршрутов НГПТ (Н2),10,5,4,NaN,14,10,NaN,NaN,NaN,7.0,"7,5"
2,Критерий класса подвижного состава НГПТ (Н3),9,5,10,NaN,14,10,NaN,NaN,NaN,9.0,7
3,Критерий интермодальности маршрута НГПТ (Н4),13,15,10,NaN,7,10,NaN,NaN,NaN,10.0,14
4,Критерий криволинейности маршрута НГПТ (Н5),6,5,4,NaN,14,5,NaN,NaN,NaN,6.0,"5,5"
5,Критерий обособленности маршрута НГПТ (У1),13,10,10,NaN,14,15,NaN,NaN,NaN,12.0,"11,5"
6,Критерий наличия мест концентрации ДТП на марш...,3,5,4,NaN,4,5,NaN,NaN,NaN,4.0,4
7,Критерий наличия неподходящих участков УДС на ...,4,10,10,NaN,5,5,NaN,NaN,NaN,6.0,7
8,Критерий доступности маршрута НГПТ для населен...,15,20,20,NaN,7,15,NaN,NaN,NaN,13.0,"17,5"
9,Критерий наличия якорных объектов притяжения в...,7,20,20,NaN,7,15,NaN,NaN,NaN,11.0,"13,5"

,Unnamed: 0,ЛЛМ,ЕП,УС,МЖ,ИР,ЛИ,АТ,АД,РХ,Unnamed: 10,Unnamed: 11
0,Критерий интервала маршрута НГПТ (Н1),20,5,8,NaN,14,10,NaN,NaN,NaN,9.0,"12,5"
1,Критерий времени работы маршрутов НГПТ (Н2),10,5,4,NaN,14,10,NaN,NaN,NaN,7.0,"7,5"
2,Критерий класса подвижного состава НГПТ (Н3),9,5,10,NaN,14,10,NaN,NaN,NaN,9.0,7
3,Критерий интермодальности маршрута НГПТ (Н4),13,15,10,NaN,7,10,NaN,NaN,NaN,10.0,14
4,Критерий криволинейности маршрута НГПТ (Н5),6,5,4,NaN,14,5,NaN,NaN,NaN,6.0,"5,5"
5,Критерий обособленности маршрута НГПТ (У1),13,10,10,NaN,14,15,NaN,NaN,NaN,12.0,"11,5"
6,Критерий наличия мест концентрации ДТП на марш...,3,5,4,NaN,4,5,NaN,NaN,NaN,4.0,4
7,Критерий наличия неподходящих участков УДС на ...,4,10,10,NaN,5,5,NaN,NaN,NaN,6.0,7
8,Критерий доступности маршрута НГПТ для населен...,15,20,20,NaN,7,15,NaN,NaN,NaN,13.0,"17,5"
9,Критерий наличия якорных объектов притяжения в...,7,20,20,NaN,7,15,NaN,NaN,NaN,11.0,"13,5"